import { Story } from 'inkjs';

import type { DialogueChoice, DialogueNode, GameState } from '../types';
import { isChoiceLocked } from '../choiceLocks';

// Generated by scripts/build-ink-story.mjs.
import storyContent from '../story/story.json';

export type InkStoryId = 'main';

export const createInkStory = (storyId: InkStoryId, stateJson?: string | null) => {
  if (storyId !== 'main') throw new Error(`Unknown Ink storyId: ${storyId}`);

  const story = new Story(storyContent as unknown as Record<string, unknown>);
  if (stateJson) story.state.LoadJson(stateJson);
  return story;
};

export const syncGameStateToInkVariables = (story: Story, state: GameState) => {
  const repByFactionId = new Map(state.factions.map(f => [f.id, f.reputation] as const));
  const vars = story.variablesState as unknown as Record<string, unknown>;

  // These variables are declared in the Ink script.
  vars.rep_iron_pact = repByFactionId.get('iron-pact') ?? 0;
  vars.rep_verdant_court = repByFactionId.get('verdant-court') ?? 0;
  vars.rep_ember_throne = repByFactionId.get('ember-throne') ?? 0;
};

const parseInkChoiceTags = (tags: string[] | null | undefined) => {
  const meta: {
    id: string | null;
    goto: string | null;
    reveal: string | null;
    effects: DialogueChoice['effects'];
    requiredReputation: DialogueChoice['requiredReputation'] | undefined;
    requiresAllSecrets: DialogueChoice['requiresAllSecrets'] | undefined;
    requiresAnySecrets: DialogueChoice['requiresAnySecrets'] | undefined;
    exclusiveGroup: DialogueChoice['exclusiveGroup'] | undefined;
    hideWhenLockedBySecrets: DialogueChoice['hideWhenLockedBySecrets'] | undefined;
    hideWhenHasAnySecrets: DialogueChoice['hideWhenHasAnySecrets'] | undefined;
  } = {
    id: null,
    goto: null,
    reveal: null,
    effects: [],
    requiredReputation: undefined,
    requiresAllSecrets: undefined,
    requiresAnySecrets: undefined,
    exclusiveGroup: undefined,
    hideWhenLockedBySecrets: undefined,
    hideWhenHasAnySecrets: undefined,
  };

  if (!tags?.length) return meta;

  for (const rawTag of tags) {
    const tag = rawTag.trim();
    if (!tag) continue;

    if (tag.startsWith('id:')) {
      meta.id = tag.slice('id:'.length).trim() || null;
      continue;
    }

    if (tag.startsWith('goto:')) {
      meta.goto = tag.slice('goto:'.length).trim() || null;
      continue;
    }

    if (tag.startsWith('reveal:')) {
      meta.reveal = tag.slice('reveal:'.length).trim() || null;
      continue;
    }

    if (tag.startsWith('rep:')) {
      const rest = tag.slice('rep:'.length);
      const [factionId, deltaRaw] = rest.split(':');
      const delta = Number(deltaRaw);
      if (factionId && Number.isFinite(delta)) {
        meta.effects.push({ factionId, reputationChange: delta });
      }
      continue;
    }

    if (tag.startsWith('reqrep:')) {
      const rest = tag.slice('reqrep:'.length);
      const [factionId, minRaw] = rest.split(':');
      const min = Number(minRaw);
      if (factionId && Number.isFinite(min)) meta.requiredReputation = { factionId, min };
      continue;
    }

    if (tag.startsWith('allsecrets:')) {
      const rest = tag.slice('allsecrets:'.length).trim();
      if (rest) meta.requiresAllSecrets = rest.split('|').map(s => s.trim()).filter(Boolean);
      continue;
    }

    if (tag.startsWith('anysecrets:')) {
      const rest = tag.slice('anysecrets:'.length).trim();
      if (rest) meta.requiresAnySecrets = rest.split('|').map(s => s.trim()).filter(Boolean);
      continue;
    }

    if (tag.startsWith('exclusive:')) {
      meta.exclusiveGroup = tag.slice('exclusive:'.length).trim() || undefined;
      continue;
    }

    if (tag === 'hideWhenLockedBySecrets') {
      meta.hideWhenLockedBySecrets = true;
      continue;
    }

    if (tag.startsWith('hideWhenHasAnySecrets:')) {
      const rest = tag.slice('hideWhenHasAnySecrets:'.length).trim();
      if (rest) meta.hideWhenHasAnySecrets = rest.split('|').map(s => s.trim()).filter(Boolean);
      continue;
    }
  }

  return meta;
};

const getStringVar = (story: Story, key: string) => {
  const vars = story.variablesState as unknown as Record<string, unknown>;
  const value = vars[key];
  return typeof value === 'string' ? value : '';
};

export const continueInkToChoicePoint = (story: Story) => {
  if (story.canContinue) story.ContinueMaximally();
};

export const buildDialogueNodeFromInk = (story: Story): DialogueNode => {
  // Ensure the story has emitted content for this point in the flow.
  continueInkToChoicePoint(story);

  const nodeId = getStringVar(story, 'cc_node_id') || 'ink:unknown';
  const speaker = getStringVar(story, 'cc_speaker') || 'Narrator';
  const speakerFaction = getStringVar(story, 'cc_faction') || undefined;

  const text = story.currentText ?? '';

  const choices: DialogueChoice[] = story.currentChoices.map(c => {
    const meta = parseInkChoiceTags(c.tags);

    return {
      id: meta.id ?? `ink:${nodeId}:${c.index}`,
      text: c.text,
      effects: meta.effects,
      nextNodeId: meta.goto ?? null,
      requiredReputation: meta.requiredReputation,
      requiresAllSecrets: meta.requiresAllSecrets,
      requiresAnySecrets: meta.requiresAnySecrets,
      exclusiveGroup: meta.exclusiveGroup,
      hideWhenLockedBySecrets: meta.hideWhenLockedBySecrets,
      hideWhenHasAnySecrets: meta.hideWhenHasAnySecrets,
      revealsInfo: meta.reveal ?? undefined,
    };
  });

  return {
    id: nodeId,
    speaker,
    speakerFaction,
    text,
    choices,
  };
};

export const getInkChoiceLockedFlags = (state: GameState, node: DialogueNode) => {
  return node.choices.map(choice => isChoiceLocked(choice, state.factions, state.knownSecrets, state.selectedChoiceIds));
};
