import { Story } from 'inkjs';

import type { DialogueChoice, DialogueNode, GameState } from '../types';
import type { GameEffect } from '../effects';
import { isChoiceLocked } from '../choiceLocks';

// Generated by scripts/build-ink-story.mjs.
import storyContent from '../story/story.json';
import storyMeta from '../story/story.meta.json';

export type InkStoryId = 'main';

export const getInkStoryVersion = (storyId: InkStoryId): string | null => {
  if (storyId !== 'main') return null;
  const maybe = (storyMeta as unknown as { storyVersion?: unknown } | null)?.storyVersion;
  return typeof maybe === 'string' ? maybe : null;
};

export const createInkStory = (storyId: InkStoryId, stateJson?: string | null) => {
  if (storyId !== 'main') throw new Error(`Unknown Ink storyId: ${storyId}`);

  const story = new Story(storyContent as unknown as Record<string, unknown>);
  if (stateJson) story.state.LoadJson(stateJson);
  return story;
};

export const syncGameStateToInkVariables = (story: Story, state: GameState) => {
  const repByFactionId = new Map(state.factions.map(f => [f.id, f.reputation] as const));
  const vars = story.variablesState as unknown as Record<string, unknown>;

  // These variables are declared in the Ink script.
  vars.rep_iron_pact = repByFactionId.get('iron-pact') ?? 0;
  vars.rep_verdant_court = repByFactionId.get('verdant-court') ?? 0;
  vars.rep_ember_throne = repByFactionId.get('ember-throne') ?? 0;
};

const parseInkChoiceTags = (tags: string[] | null | undefined) => {
  const meta: {
    id: string | null;
    goto: string | null;
    reveal: string | null;
    effects: DialogueChoice['effects'];
    gameEffects: GameEffect[];
    requiredReputation: DialogueChoice['requiredReputation'] | undefined;
    requiresAllSecrets: DialogueChoice['requiresAllSecrets'] | undefined;
    requiresAnySecrets: DialogueChoice['requiresAnySecrets'] | undefined;
    exclusiveGroup: DialogueChoice['exclusiveGroup'] | undefined;
    hideWhenLockedBySecrets: DialogueChoice['hideWhenLockedBySecrets'] | undefined;
    hideWhenHasAnySecrets: DialogueChoice['hideWhenHasAnySecrets'] | undefined;
  } = {
    id: null,
    goto: null,
    reveal: null,
    effects: [],
    gameEffects: [],
    requiredReputation: undefined,
    requiresAllSecrets: undefined,
    requiresAnySecrets: undefined,
    exclusiveGroup: undefined,
    hideWhenLockedBySecrets: undefined,
    hideWhenHasAnySecrets: undefined,
  };

  if (!tags?.length) return meta;

  for (const rawTag of tags) {
    const tag = rawTag.trim();
    if (!tag) continue;

    if (tag.startsWith('id:')) {
      meta.id = tag.slice('id:'.length).trim() || null;
      continue;
    }

    if (tag.startsWith('goto:')) {
      meta.goto = tag.slice('goto:'.length).trim() || null;
      continue;
    }

    if (tag.startsWith('reveal:')) {
      meta.reveal = tag.slice('reveal:'.length).trim() || null;
      continue;
    }

    if (tag.startsWith('rep:')) {
      const rest = tag.slice('rep:'.length);
      const [factionId, deltaRaw] = rest.split(':');
      const delta = Number(deltaRaw);
      if (factionId && Number.isFinite(delta)) {
        meta.effects.push({ factionId, reputationChange: delta });
      }
      continue;
    }

    if (tag.startsWith('res:')) {
      const rest = tag.slice('res:'.length);
      const [resourceIdRaw, deltaRaw] = rest.split(':');
      const resourceId = (resourceIdRaw ?? '').trim();
      const delta = Number(deltaRaw);
      if (
        (resourceId === 'coin' || resourceId === 'influence' || resourceId === 'supplies' || resourceId === 'intel') &&
        Number.isFinite(delta)
      ) {
        meta.gameEffects.push({ kind: 'resource', resourceId, delta });
      }
      continue;
    }

    if (tag.startsWith('milestone:')) {
      const id = tag.slice('milestone:'.length).trim();
      if (id) meta.gameEffects.push({ kind: 'milestone:add', id });
      continue;
    }

    if (tag.startsWith('proj:start:')) {
      const templateId = tag.slice('proj:start:'.length).trim();
      if (templateId) meta.gameEffects.push({ kind: 'project:start', templateId });
      continue;
    }

    if (tag.startsWith('proj:pause:')) {
      const projectId = tag.slice('proj:pause:'.length).trim();
      if (projectId) meta.gameEffects.push({ kind: 'project:pause', projectId });
      continue;
    }

    if (tag.startsWith('proj:pauseByTemplate:')) {
      const templateId = tag.slice('proj:pauseByTemplate:'.length).trim();
      if (templateId) meta.gameEffects.push({ kind: 'project:pauseByTemplate', templateId });
      continue;
    }

    if (tag.startsWith('proj:resume:')) {
      const projectId = tag.slice('proj:resume:'.length).trim();
      if (projectId) meta.gameEffects.push({ kind: 'project:resume', projectId });
      continue;
    }

    if (tag.startsWith('proj:resumeByTemplate:')) {
      const templateId = tag.slice('proj:resumeByTemplate:'.length).trim();
      if (templateId) meta.gameEffects.push({ kind: 'project:resumeByTemplate', templateId });
      continue;
    }

    if (tag.startsWith('proj:cancel:')) {
      const projectId = tag.slice('proj:cancel:'.length).trim();
      if (projectId) meta.gameEffects.push({ kind: 'project:cancel', projectId });
      continue;
    }

    if (tag.startsWith('proj:cancelByTemplate:')) {
      const templateId = tag.slice('proj:cancelByTemplate:'.length).trim();
      if (templateId) meta.gameEffects.push({ kind: 'project:cancelByTemplate', templateId });
      continue;
    }

    if (tag.startsWith('proj:accelerate:')) {
      const rest = tag.slice('proj:accelerate:'.length);
      const [projectIdRaw, deltaTurnsRaw] = rest.split(':');
      const projectId = (projectIdRaw ?? '').trim();
      const deltaTurns = Number(deltaTurnsRaw);
      if (projectId && Number.isFinite(deltaTurns)) {
        meta.gameEffects.push({ kind: 'project:accelerate', projectId, deltaTurns });
      }
      continue;
    }

    if (tag.startsWith('proj:accelerateByTemplate:')) {
      const rest = tag.slice('proj:accelerateByTemplate:'.length);
      const [templateIdRaw, deltaTurnsRaw] = rest.split(':');
      const templateId = (templateIdRaw ?? '').trim();
      const deltaTurns = Number(deltaTurnsRaw);
      if (templateId && Number.isFinite(deltaTurns)) {
        meta.gameEffects.push({ kind: 'project:accelerateByTemplate', templateId, deltaTurns });
      }
      continue;
    }

    if (tag.startsWith('tension:')) {
      const rest = tag.slice('tension:'.length);
      const [aRaw, bRaw, deltaRaw] = rest.split(':');
      const a = (aRaw ?? '').trim();
      const b = (bRaw ?? '').trim();
      const delta = Number(deltaRaw);
      if (a && b && Number.isFinite(delta)) meta.gameEffects.push({ kind: 'tension', a, b, delta });
      continue;
    }

    if (tag.startsWith('route:')) {
      const rest = tag.slice('route:'.length);
      const [routeIdRaw, statusRaw, untilTurnRaw, embargoedByRaw] = rest.split(':');
      const routeId = (routeIdRaw ?? '').trim();
      const status = (statusRaw ?? '').trim();
      const untilTurn = untilTurnRaw != null ? Number(untilTurnRaw) : NaN;
      const embargoedBy = (embargoedByRaw ?? '').trim();

      if (routeId && (status === 'open' || status === 'embargoed' || status === 'raided')) {
        meta.gameEffects.push({
          kind: 'tradeRoute:setStatus',
          routeId,
          status: status as 'open' | 'embargoed' | 'raided',
          untilTurn: Number.isFinite(untilTurn) ? untilTurn : undefined,
          embargoedBy: embargoedBy || undefined,
        });
      }

      continue;
    }

    if (tag.startsWith('region:')) {
      const rest = tag.slice('region:'.length);
      const [regionIdRaw, controlRaw, contestedRaw] = rest.split(':');
      const regionId = (regionIdRaw ?? '').trim();
      const control = (controlRaw ?? '').trim();

      let contested: boolean | undefined;
      const c = (contestedRaw ?? '').trim().toLowerCase();
      if (c === 'contested' || c === 'true' || c === '1') contested = true;
      else if (c === 'uncontested' || c === 'false' || c === '0') contested = false;

      if (regionId && control) {
        meta.gameEffects.push({ kind: 'region:setControl', regionId, control, contested });
      }

      continue;
    }

    if (tag.startsWith('log:')) {
      const message = tag.slice('log:'.length).trim();
      if (message) meta.gameEffects.push({ kind: 'log', message });
      continue;
    }

    if (tag.startsWith('reqrep:')) {
      const rest = tag.slice('reqrep:'.length);
      const [factionId, minRaw] = rest.split(':');
      const min = Number(minRaw);
      if (factionId && Number.isFinite(min)) meta.requiredReputation = { factionId, min };
      continue;
    }

    if (tag.startsWith('allsecrets:')) {
      const rest = tag.slice('allsecrets:'.length).trim();
      if (rest) meta.requiresAllSecrets = rest.split('|').map(s => s.trim()).filter(Boolean);
      continue;
    }

    if (tag.startsWith('anysecrets:')) {
      const rest = tag.slice('anysecrets:'.length).trim();
      if (rest) meta.requiresAnySecrets = rest.split('|').map(s => s.trim()).filter(Boolean);
      continue;
    }

    if (tag.startsWith('exclusive:')) {
      meta.exclusiveGroup = tag.slice('exclusive:'.length).trim() || undefined;
      continue;
    }

    if (tag === 'hideWhenLockedBySecrets') {
      meta.hideWhenLockedBySecrets = true;
      continue;
    }

    if (tag.startsWith('hideWhenHasAnySecrets:')) {
      const rest = tag.slice('hideWhenHasAnySecrets:'.length).trim();
      if (rest) meta.hideWhenHasAnySecrets = rest.split('|').map(s => s.trim()).filter(Boolean);
      continue;
    }
  }

  return meta;
};

const getStringVar = (story: Story, key: string) => {
  const vars = story.variablesState as unknown as Record<string, unknown>;
  const value = vars[key];
  return typeof value === 'string' ? value : '';
};

export const continueInkToChoicePoint = (story: Story) => {
  if (story.canContinue) story.ContinueMaximally();
};

export const buildDialogueNodeFromInk = (story: Story): DialogueNode => {
  // Ensure the story has emitted content for this point in the flow.
  continueInkToChoicePoint(story);

  const nodeId = getStringVar(story, 'cc_node_id') || 'ink:unknown';
  const speaker = getStringVar(story, 'cc_speaker') || 'Narrator';
  const speakerFaction = getStringVar(story, 'cc_faction') || undefined;

  const text = story.currentText ?? '';

  const choices: DialogueChoice[] = story.currentChoices.map(c => {
    const meta = parseInkChoiceTags(c.tags);

    return {
      id: meta.id ?? `ink:${nodeId}:${c.index}`,
      text: c.text,
      effects: meta.effects,
      gameEffects: meta.gameEffects.length ? meta.gameEffects : undefined,
      nextNodeId: meta.goto ?? null,
      requiredReputation: meta.requiredReputation,
      requiresAllSecrets: meta.requiresAllSecrets,
      requiresAnySecrets: meta.requiresAnySecrets,
      exclusiveGroup: meta.exclusiveGroup,
      hideWhenLockedBySecrets: meta.hideWhenLockedBySecrets,
      hideWhenHasAnySecrets: meta.hideWhenHasAnySecrets,
      revealsInfo: meta.reveal ?? undefined,
    };
  });

  return {
    id: nodeId,
    speaker,
    speakerFaction,
    text,
    choices,
  };
};

export const getInkChoiceLockedFlags = (state: GameState, node: DialogueNode) => {
  return node.choices.map(choice => isChoiceLocked(choice, state.factions, state.knownSecrets, state.selectedChoiceIds));
};
